In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
# Code adapted from Dr. Kesselly Kamara's Panopto presentation for Market Basket Analysis

In [3]:
# importing and cleaning our data
market_basket = pd.read_csv("teleco_market_basket.csv")
print(market_basket.shape)

# nix empty rows, people who didn't buy anything
market_basket = market_basket.dropna(axis = 0, how = "all")

# check shape again
print(market_basket.shape)
market_basket

(15002, 20)
(7501, 20)

,Item01,Item02,Item03,Item04,Item05,Item06,Item07,Item08,Item09,Item10,Item11,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20
1,Logitech M510 Wireless mouse,HP 63 Ink,HP 65 ink,nonda USB C to USB Adapter,10ft iPHone Charger Cable,HP 902XL ink,Creative Pebble 2.0 Speakers,Cleaning Gel Universal Dust Cleaner,Micro Center 32GB Memory card,YUNSONG 3pack 6ft Nylon Lightning Cable,TopMate C5 Laptop Cooler pad,Apple USB-C Charger cable,HyperX Cloud Stinger Headset,TONOR USB Gaming Microphone,Dust-Off Compressed Gas 2 pack,3A USB Type C Cable 3 pack 6FT,HOVAMP iPhone charger,SanDisk Ultra 128GB card,FEEL2NICE 5 pack 10ft Lighning cable,FEIYOLD Blue light Blocking Glasses
3,Apple Lightning to Digital AV Adapter,TP-Link AC1750 Smart WiFi Router,Apple Pencil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,UNEN Mfi Certified 5-pack Lightning Cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Cat8 Ethernet Cable,HP 65 ink,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Dust-Off Compressed Gas 2 pack,Screen Mom Screen Cleaner kit,Moread HDMI to VGA Adapter,HP 62XL Tri-Color ink,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14993,SanDisk 32GB Ultra SDHC card,Vsco 70 pack stickers,SanDisk 128GB microSDXC card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14995,Apple Lightning to Digital AV Adapter,Nylon Braided Lightning to USB cable,Apple Pencil,USB 2.0 Printer cable,ARRIS SURFboard SB8200 Cable Modem,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14997,Falcon Dust Off Compressed Gas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,HP 63XL Ink,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15001,Apple Pencil,SanDisk Ultra 128GB card,RUNMUS Gaming Headset,TopMate C5 Laptop Cooler pad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# making the dataframe a list of lists
basket_list = []

for i in range (0, 7501):
    basket_list.append([str(market_basket.values[i,j]) for j in range (0, 20)])


print(len(basket_list[0]))

20

In [7]:
# transaction encoder time
encoder = TransactionEncoder()
encoded_basket = encoder.fit(basket_list).transform(basket_list)

# back to a dataframe to analyze it better
encoded_df = pd.DataFrame(encoded_basket, columns = encoder.columns_)

print(encoded_df.columns)

Index(['10ft iPHone Charger Cable', '10ft iPHone Charger Cable 2 Pack',
       '3 pack Nylon Braided Lightning Cable',
       '3A USB Type C Cable 3 pack 6FT', '5pack Nylon Braided USB C cables',
       'ARRIS SURFboard SB8200 Cable Modem', 'Anker 2-in-1 USB Card Reader',
       'Anker 4-port USB hub', 'Anker USB C to HDMI Adapter',
       'Apple Lightning to Digital AV Adapter',
       ...
       'iFixit Pro Tech Toolkit', 'iPhone 11 case', 'iPhone 12 Charger cable',
       'iPhone 12 Pro case', 'iPhone 12 case',
       'iPhone Charger Cable Anker 6ft', 'iPhone SE case', 'nan',
       'nonda USB C to USB Adapter', 'seenda Wireless mouse'],
      dtype='object', length=120)

In [8]:
# remove our "nan" column from the encoded data
cleaned_basket = encoded_df.drop(["nan"], axis = 1)
cleaned_basket

# export a csv
cleaned_basket.to_csv("cleaned_basket.csv")

In [9]:
# discover top 10 most popular products
prod_count = cleaned_basket.loc[:,:].sum()
popular = prod_count.sort_values(axis = 0, ascending = False).head(10)
print(popular)

Dust-Off Compressed Gas 2 pack          1788
Apple Pencil                            1348
VIVO Dual LCD Monitor Desk mount        1306
USB 2.0 Printer cable                   1282
HP 61 ink                               1229
Apple USB-C Charger cable                991
Screen Mom Screen Cleaner kit            972
SanDisk Ultra 64GB card                  737
Nylon Braided Lightning to USB cable     715
Stylus Pen for iPad                      713
dtype: int64

In [10]:
# executing the Apriori algorithm

rules = apriori(cleaned_basket, min_support = 0.02, use_colnames = True)
rules.head(10)

    support                                 itemsets
0  0.050527       (10ft iPHone Charger Cable 2 Pack)
1  0.042528         (3A USB Type C Cable 3 pack 6FT)
2  0.029463           (Anker 2-in-1 USB Card Reader)
3  0.068391            (Anker USB C to HDMI Adapter)
4  0.087188  (Apple Lightning to Digital AV Adapter)
5  0.179709                           (Apple Pencil)
6  0.132116              (Apple USB-C Charger cable)
7  0.062525                    (Cat8 Ethernet Cable)
8  0.031862    (Cleaning Gel Universal Dust Cleaner)
9  0.238368         (Dust-Off Compressed Gas 2 pack)

In [ ]:
# rule table creation

rule_table = association_rules(rules, metric = "lift", min_threshold = 1)
rule_table.head(5)

In [ ]:
print("Support values:\n",rule_table["support"])
print("Confidence values:\n",rule_table["confidence"])
print("Lift values:\n",rule_table["lift"])

In [ ]:
# top 3 support

top_support = rule_table.sort_values("support", ascending = False).head(3)
top_support

In [ ]:
# top 3 confidence

top_confidence = rule_table.sort_values("confidence", ascending = False).head(3)
top_confidence

In [ ]:
# top 3 lift

top_lift = rule_table.sort_values("lift", ascending = False).head(3)
top_lift